[package]
name = "redis"
version = "1.0.0"
authors = ["Javohir Abdusattorov <jvhrdeveloper@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.13.0"
rand = "0.9.0"
anyhow = "1.0.59"
bytes = "1.3.0"
thiserror = "1.0.32"
tokio = { version = "1.23.0", features = ["full"] }
fast-glob = "0.4.3"